### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by TheDragonRing** [TheDragonRing/QuickJoinMsg#4]
There is this problem in Main.php - i am working on it but will welcome help!

    PHP Parse error: syntax error, unexpected ';' in /var/www/tmp/5/QuickJoinMsg/src/TheDragonRing/QuickJoinMsg/Main.php on line 97
    Errors parsing /var/www/tmp/5/QuickJoinMsg/src/TheDragonRing/QuickJoinMsg/Main.php

**Comment by applqpak** [comment]
Oke. I'll take a look.
