### ISSUE TITLE
member function get() on null

### ISSUE THREAD

**Issue by TheDragonRing** [TheDragonRing/QuickJoinMsg#6]
Someone from the ImagicalMine forums tested the plugin and said that this error came up, I've asked him if he has anymore information on the error but so far there is just this:

critical> Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'QuickJoinMsg v1.0.0': Call to a member function get() on null on TheDragonRing\QuickJoinMsg

**Comment by applqpak** [comment]
Lemme take a look.

**Comment by applqpak** [comment]
Ok, I got it. Lemme fix it. You're calling to $this->config->get("JoinMsg") when $this->config doesn't exist. It should be $this->yml. I'll update it now!

**Comment by applqpak** [comment]
Updated.

**Comment by TheDragonRing** [comment]
Oops lol
